version: "0.2"
dictionaryDefinitions: []
dictionaries: []
ignoreWords: []
flagWords: []
import: []
ignorePaths:
  - .github/**
  - build/**
  - LICENSE*
  - "*.json"
words:
  - antiope
  - iphydf
  - robinlinden
  - tokhub
