#!/bin/sh

set -eux

# Upgrade versions.
flutter pub upgrade --major-versions

# Make sure we have all packages downloaded.
flutter pub get

# Generate the database (drift) code.
dart run build_runner build --delete-conflicting-outputs
