name: ci

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]

# Cancel old builds when pushing new commits.
concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  common:
    uses: TokTok/ci-tools/.github/workflows/common-ci.yml@master

  prepare:
    name: Prepare
    uses: TokTok/ci-tools/.github/workflows/deploy-prepare.yml@master

  flutter:
    name: Flutter
    needs: [prepare]
    uses: TokTok/ci-tools/.github/workflows/flutter.yml@master
    with:
      project-name: tokhub
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
