name: pages

on:
  push:
    branches: ["master"]

  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.29.0"

# Cancel old builds when pushing new commits.
concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-pages:
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      id-token: write
      pages: write

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Build content
        run: |
          ./tools/prepare-web
          flutter build web --base-href "/tokhub/"

      - name: Set-up Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
