name: pages

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  pages:
    name: Pages
    uses: TokTok/ci-tools/.github/workflows/flutter-pages.yml@master
    with:
      project-name: tokhub
